### ISSUE TITLE
Toggling global classes is a bad code smell

### ISSUE THREAD

**Issue by danielpclark** [danielpclark/state_inspector#2]
I found out the hard way that using a method to indiscriminately toggle between true and false can lead to bad results.

The toggle_informant method will be changed to:

```ruby
def toggle_informant informant=true
  @informant = informant
end
```

This will remove sporadic behavior possibilities.

**Comment by zenspider** [comment]
I've got a cleaner patch coming...

**Comment by zenspider** [comment]
Submitted #3.
